#  Templ
image: node:16

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - npm install 
              - npm audit fix --force
              -npm install react@17.0.1

        
            caches:
              - node
