#  Template N
image: node:16

image: node:16

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - npm install -g npm@latest
              - npm audit fix --force
              #- npm test
              -npm install react@17.0.1
              -npm-force-resolutions
        
            caches:
              - node
