#  Template NodeJS build


image: node:16

pipelines:
  default:
    - parallel:
        - step:
            name: Build 
            caches:
              - node
            script:
              - npm install
              - 
        - step:
