apiVersion: v1
kind: Service
metadata:
  name:  POD_NAME
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: POD_NAME
spec:
  type: NodePort
  selector:
    app: POD_NAME
  ports:
    - name: service-port-cons-int
      port: 443
      targetPort: 8080